[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
# family = "JetBrainsMono Nerd Font"
# family = "Maple Mono Normal NF CN"
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
# family = "JetBrainsMono Nerd Font"
# family = "Maple Mono Normal NF CN"
family = "Maple Mono NF CN"
style = "Bold Italic"

[font.italic]
# family = "JetBrainsMono Nerd Font"
# family = "Maple Mono Normal NF CN"
family = "Maple Mono NF CN"
style = "Italic"

[font.normal]
# family = "JetBrainsMono Nerd Font"
# family = "Maple Mono Normal NF CN"
family = "Maple Mono NF CN"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[cursor.style]
shape = "Block"
blinking = "Off"

[cursor]
vi_mode_style = "None"
unfocused_hollow = false

[window]
opacity = 0.85

[general]
live_config_reload = true
import = ["~/.config/alacritty/tokyonight_storm.toml"]
